

export type UserRole = 'admin' | 'cashier' | 'seller' | 'auditor' | 'readonly';

export type User = {
  id: string;
  name: string;
  username: string;
  password?: string;
  role: UserRole;
  avatarUrl: string;
};

export type NewUser = Omit<User, 'id'>;
export type UpdatableUser = Partial<Omit<User, 'id' | 'username' | 'password'>>;


export type TicketStatus = 'available' | 'sold' | 'redeemed' | 'void';

export type Ticket = {
  id: string;
  uniqueCode: string;
  qrCodeUrl: string;
  status: TicketStatus;
  price: number;
  issuedAt: string;
  soldAt?: string;
  redeemedAt?: string;
  orderId?: string;
};

export type OrderStatus = 'pending' | 'paid' | 'cancelled';

export type Order = {
  id: string;
  ticketIds: string[];
  totalAmount: number;
  status: OrderStatus;
  createdAt: string;
  paidAt?: string;
  sellerId: string;
  sellerName: string;
};

export type CashboxStatus = 'open' | 'closed';

export type CashboxSession = {
  id: string;
  userId: string;
  userName: string;
  status: CashboxStatus;
  openingBalance: number;
  closingBalance?: number;
  openedAt: string;
  closedAt?: string;
  totalSales: number;
};

export type AuditLogAction = 'TICKET_ISSUE' | 'TICKET_SELL' | 'TICKET_REDEEM' | 'TICKET_VOID' | 'CASHBOX_OPEN' | 'CASHBOX_CLOSE' | 'USER_ROLE_CHANGE' | 'PAYMENT_CONFIRM';

export type AuditLog = {
  id: string;
  timestamp: string;
  userId: string;
  userName:string;
  action: AuditLogAction;
  details: string;
};

export type Product = {
    id: string;
    name: string;
    price: number;
    stock: number;
    imageUrl: string;
    imageHint: string;
    isSelfService: boolean;
    isPosAvailable: boolean; // New field for Point of Sale availability
};

// Represents an item in the shopping cart, stored within a Purchase
export type CartItem = {
  id: string; // Corresponds to Product ID
  name: string;
  price: number;
  quantity: number;
  type: 'product' | 'ticket';
  returned?: boolean; // Flag to indicate if the item has been returned
};

// Represents a completed purchase record in Firestore
export type Purchase = {
  id: string; // Firestore document ID
  date: string;
  total: number;
  items: Omit<CartItem, 'type'>[];
  cedula: string;
  celular: string;
  sellerId?: string; // ID of the user who made the sale in POS
  sellerName?: string; // Name of the user who made the sale in POS
};

// Type for creating a new purchase, ID is generated by Firestore
export type NewPurchase = Omit<Purchase, 'id'>;

// Represents a record of a product return
export type Return = {
  id: string; // Firestore document ID
  productId: string;
  productName: string;
  quantity: number;
  returnedAt: string; // Timestamp of the return
  processedByUserId: string; // Who processed the return
  processedByUserName: string;
};

// Type for creating a new return record
export type NewReturn = Omit<Return, 'id'>;
